
spring:
  application:
    name: test-app
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        service-id: config-server
        enabled: true
        #这里拉取配置是自动按照模块名字.yml匹配的，所以不需要额外加上配置名字
        #拉取的时机是本微服务启动时即时拉取，build中生成的运行配置文件是在拉取不到远程配置时的后备使用。因此每次某个项目修改完配置文件后，直接重启本项目即可

server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    prefer-ip-address: true
